server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/blog_app_apis
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  security:
#    user:
#      name: Anshu
#      password: Anshu
#      roles: ADMIN


Project:
  Image: images/

logging:
  level:
    org:
      springframework:
        security: DEBUG











